### ISSUE TITLE
[Bug]: Custom Headers are not being set

### ISSUE THREAD

**Issue by kkarkos** [unclecode/crawl4ai#1258]
### crawl4ai version

0.6.3

### Expected Behavior

As per website example there should be two ways of passing custom headers -> https://docs.crawl4ai.com/advanced/advanced-features/#4-custom-headers . However, both are not working.

### Current Behavior

Passed headers are not shown.

```
Server output for headers of below examples:
=== CRAWLER REQUEST DETAILS ===
Timestamp: 2025-06-30T02:26:48.786Z
Method: GET
URL: /crawl-test
IP Address: ::1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/116.0.0.0 Safari/537.36

Headers:
  host: 17cb-103-53-118-171.ngrok-free.app
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/116.0.0.0 Safari/537.36
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
  accept-encoding: gzip, deflate, br, zstd
  accept-language: en-GB,en;q=0.9
  cookie: cookiesEnabled=true
  priority: u=0, i
  sec-ch-ua: "Chromium";v="116", "Not_A Brand";v="8", "Google Chrome";v="116"
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: "Linux"
  sec-fetch-dest: document
  sec-fetch-mode: navigate
  sec-fetch-site: none
  sec-fetch-user: ?1
  upgrade-insecure-requests: 1
  x-forwarded-for: 103.53.118.170
  x-forwarded-host: 17cb-103-53-118-170.ngrok-free.app
  x-forwarded-proto: https
===============================


=== CRAWLER REQUEST DETAILS ===
Timestamp: 2025-06-30T02:26:49.753Z
Method: GET
URL: /crawl-test
IP Address: ::1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/116.0.0.0 Safari/537.36

Headers:
  host: 17cb-103-53-118-171.ngrok-free.app
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/116.0.0.0 Safari/537.36
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
  accept-encoding: gzip, deflate, br, zstd
  accept-language: en-GB,en;q=0.9
  cookie: cookiesEnabled=true
  if-none-match: W/"5d8-zfDCp11ZgYqVSztGjPjYWAnOCEI"
  priority: u=0, i
  sec-ch-ua: "Chromium";v="116", "Not_A Brand";v="8", "Google Chrome";v="116"
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: "Linux"
  sec-fetch-dest: document
  sec-fetch-mode: navigate
  sec-fetch-site: none
  sec-fetch-user: ?1
  upgrade-insecure-requests: 1
  x-forwarded-for: 103.53.118.170
  x-forwarded-host: 17cb-103-53-118-170.ngrok-free.app
  x-forwarded-proto: https
===============================
```

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash

```

### Steps to Reproduce

```bash
1. Use code below or original example from website
```

### Code snippets

```python
import asyncio
from crawl4ai import AsyncWebCrawler

async def custom_headers_example():
    """Example of using custom headers in different ways"""
    
    # Method 1: Headers via arun()
    crawler1 = AsyncWebCrawler()
    result1 = await crawler1.arun(
        url="https://httpbin.org/headers",
        headers={
            "Accept-Language": "en-US,en;q=0.9",
            "User-Agent": "CustomBot/1.0"
        }
    )
    print("Method 1 - Headers via arun():")
    print(f"Success: {result1.success}")
    
    # Method 2: Headers via crawler strategy (if supported)
    crawler2 = AsyncWebCrawler()
    if hasattr(crawler2.crawler_strategy, 'set_custom_headers'):
        crawler2.crawler_strategy.set_custom_headers({
            "Accept-Language": "fr-FR,fr;q=0.9"
        })
        result2 = await crawler2.arun("https://httpbin.org/headers")
        print("Method 2 - Headers via strategy:")
        print(f"Success: {result2.success}")
    
    return result1

if __name__ == "__main__":
    asyncio.run(custom_headers_example())
```

### OS

macOS

### Python version

3.11

### Browser

N/A
