### ISSUE TITLE
[Bug]: In Docker setup: Failed to start browser: [Errno 2] No such file or directory: 'google-chrome'

### ISSUE THREAD

**Issue by betterthanever2** [unclecode/crawl4ai#875]
### crawl4ai version

latest available via docker hub

### Expected Behavior

I would expect the docker image to contain all required dependencies from the get-go

### Current Behavior

I get the error `Failed to start browser: [Errno 2] No such file or directory: 'google-chrome'` whenever trying to submit a task to the crawl4ai docker container.

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash

```

### Steps to Reproduce

```bash
1. Start crawl4ai docker image
2. Try submitting a task
```

### Code snippets

```python
My docker compose file:

services:
  crawl4ai:
    image: unclecode/crawl4ai:${VERSION:-all}-amd64
    container_name: crawl4ai
    profiles: ["hub-amd64"]
    ports:
      - 51235:11235
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: always
    networks:
      - wcore_intranet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wcore_intranet:
    external: true
```

### OS

Ubuntu-22 (host)

### Python version

3.10.15

### Error logs & Screenshots (if applicable)

I tried running the playwright installation commands inside the container, but those that succeeded didn't help, and those that didn't complained about a bunch of missing libraries on the host system.

I can see notes about the deprecation of the current docker setup and upcoming new one, but those messages seem to be a couple of months old. Is the instruction at https://docs.crawl4ai.com/core/docker-deployment/ about the deprecated flow?

When can the new docker deployment flow be expected? Is there, possibly, a workaround to this issue with the browser inside the container?

**Comment by Darkshadenl** [comment]
I have the same error. Same setup as you.

**Comment by betterthanever2** [comment]
@unclecode @aravindkarnam FYI, the link https://docs.crawl4ai.com/deploy/docker/README.md is 404

**Comment by unclecode** [comment]
@betterthanever2 plz check this url https://github.com/unclecode/crawl4ai/blob/main/deploy/docker/README.md

Follow this one first plz

**Comment by betterthanever2** [comment]
Ok, I managed to start up the service. 

There is a minor error in the docs: you want to build/run from root, **not** from `./deploy` directory.

My compose file based on this setup (generated by llm from the doc):
```
services:
  crawl4ai:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
        INSTALL_TYPE: "all"
        ENABLE_GPU: "false"
        APP_HOME: "/app"
      platforms:
        - "linux/amd64"
    ports:
      - 51235:8000
    env_file:
      - .llm.env
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
```

Later I will report as to how the crawling goes.
